---
name: Xacobeo
version: 0.03_03
author:
  - 'Emmanuel Rodriguez <potyl@cpan.org>'
abstract: XPath (XML Path Language) visualizer.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  Glib: 0
  Gtk2: 0
  Gtk2::GladeXML: 0
  Pod::Usage: 0
  Time::HiRes: 0
  XML::LibXML: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
provides:
  Xacobeo:
    file: lib/Xacobeo.pm
    version: 0.03_03
  Xacobeo::Document:
    file: lib/Xacobeo/Document.pm
  Xacobeo::DomModel:
    file: lib/Xacobeo/DomModel.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
