---
name: Xacobeo
version: 0.10
author:
  - 'Emmanuel Rodriguez <potyl@cpan.org>'
abstract: XPath (XML Path Language) visualizer.
license: perl
resources:
  bugtracker: http://code.google.com/p/xacobeo/issues/list
  homepage: http://code.google.com/p/xacobeo/
  license: http://dev.perl.org/licenses/
  repository: http://code.google.com/p/xacobeo/source/browse/
configure_requires:
  ExtUtils::Depends: 0
  ExtUtils::ParseXS: 0
  ExtUtils::PkgConfig: 0
  File::Path: 0
  File::Spec::Functions: 0
  Gtk2: 0
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Data::Dumper: 0
  DynaLoader: 0
  English: 0
  Exporter: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  Glib: 0
  Gtk2: 0
  Gtk2::GladeXML: 0
  Gtk2::SourceView2: 0
  Locale::TextDomain: 0
  Pod::Usage: 0
  Time::HiRes: 0
  XML::LibXML: 0
  parent: 0
  perl: 5.6.1
build_requires:
  ExtUtils::Depends: 0
  ExtUtils::ParseXS: 0
  ExtUtils::PkgConfig: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Gtk2: 0
  Test::Exception: 0
  Test::More: 0
provides:
  Xacobeo:
    file: lib/Xacobeo.pm
    version: 0.10
  Xacobeo::Document:
    file: lib/Xacobeo/Document.pm
  Xacobeo::DomModel:
    file: lib/Xacobeo/DomModel.pm
  Xacobeo::Error:
    file: lib/Xacobeo/Error.pm
  Xacobeo::I18n:
    file: lib/Xacobeo/I18n.pm
  Xacobeo::Timer:
    file: lib/Xacobeo/Timer.pm
  Xacobeo::UI:
    file: lib/Xacobeo/UI.pm
  Xacobeo::Utils:
    file: lib/Xacobeo/Utils.pm
  Xacobeo::XS:
    file: lib/Xacobeo/XS.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
